### ISSUE TITLE
Android 14 error on MacOs 10.4

### ISSUE THREAD

**Issue by lvm12** [epicstudios856/Vectras-VM-Android#10]
Time Of Crash :    2024_03_07-23_04_22
Device :    samsung, SM-S921B
Android Version :    14 (34)
App Version :    v2.8-debug-build-3 (13)
Kernel :    /proc/version: open failed: EACCES (Permission denied)
Support Abis :    [arm64-v8a]
Fingerprint :    samsung/e1sxeea/e1s:14/UP1A.231005.007/S921BXXU1AXB5:user/release-keys

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.androidVNC.RfbProto.writeKeyEvent(int, int, boolean)' on a null object reference
	at android.androidVNC.VncCanvas.sendMetaKey1(VncCanvas.java:1192)
	at com.vectras.qemu.MainVNCActivity$43.run(MainVNCActivity.java:1225)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by epicstudios856** [comment]
@lvm12 Ok currently thats not issue with vm just ignore and restart the app

**Comment by epicstudios856** [comment]
issue fixed here!
https://github.com/epicstudios856/Vectras-VM-Android/releases/tag/v2.8.5
