### ISSUE TITLE
Can't setup on Poco F6

### ISSUE THREAD

**Issue by McKpol** [epicstudios856/Vectras-VM-Android#100]
![Screenshot_2024-06-06-19-24-07-623_com.vectras.vm.jpg](https://github.com/epicstudios856/Vectras-VM-Android/assets/104125769/84648ffa-15bb-490c-9425-8a49e5902c87)

**Comment by epicstudios856** [comment]
cpu not supported

**Comment by McKpol** [comment]
It's because the Instructions set is Arm9.2-a?
Are you gonna add support for these or is it too complex to add in a short period of time?

**Comment by McKpol** [comment]
> cpu not supported

It's because the Instructions set is Arm9.2-a?
Are you gonna add support for these or is it too complex to add in a short period of time?
