### ISSUE TITLE
ENOENT 

### ISSUE THREAD

**Issue by hyperdyn-ai** [epicstudios856/Vectras-VM-Android#11]
When I opened the app it's showing like this 

java.io.FileNotFoundException: / storage/emulated/0/Android/data/ com.vectras.vm/files/data/Vectras/ roms-data.json: open failed: ENOENT (No such file or directory)

**Comment by epicstudios856** [comment]
@hyperdyn-ai U need internet connection before opening the app

**Comment by hyperdyn-ai** [comment]
I have that

**Comment by epicstudios856** [comment]
@hyperdyn-ai try another version

**Comment by epicstudios856** [comment]
If its home page ignore it

If its in rom manager check internet
