### ISSUE TITLE
cant download rom

### ISSUE THREAD

**Issue by BillNye465** [epicstudios856/Vectras-VM-Android#12]
it got error too many download that file

![Screenshot_20240311_191842](https://github.com/epicstudios856/Vectras-VM-Android/assets/85538229/37a7efc1-f791-4322-8cb2-0378783cd1d3)

**Comment by epicstudios856** [comment]
@BillNye465 Sorry for thats
U need to login in g drive till we get a good server

**Comment by LucaBarbaLata** [comment]
> @BillNye465 Sorry for thats
> U need to login in g drive till we get a good server

Make it so we can download from the website

**Comment by LucaBarbaLata** [comment]
> Sorry we still haven't any server
> We are working on it
> 
> The solution:
> Login with ur gmail to g drive
> 
> 
> Thank u

U can put it on github on releases on another repo

**Comment by epicstudios856** [comment]
@LucaBarbaLata Sorry
Github limits the uploads

**Comment by LucaBarbaLata** [comment]
Compress it? Using winrar?

Like the github upload limit is 2 gb

**Comment by epicstudios856** [comment]
@LucaBarbaLata All files already compressed in higher compression with vbi


Sorry github is bad idea

**Comment by LucaBarbaLata** [comment]
> with

K
