### ISSUE TITLE
Why is there a login in requirement?

### ISSUE THREAD

**Issue by jimkoutso2008** [epicstudios856/Vectras-VM-Android#2]
I decided to try this and it tells me to login
The hell are you supposed to do with my email?

**Comment by epicstudios856** [comment]
Lol we are planning to make the app community for gamers and devs i use firebase for login and this open source lol 😂😂 im not needs your fuckin data you are not important for me bro

**Comment by Neo-vortex** [comment]
with all respect
@epicstudios856 
is right.
the login page is a bit dodgy
you can at least make it clear with a notice or privacy agreement

**Comment by jimkoutso2008** [comment]
> Lol we are planning to make the app community for gamers and devs i use firebase for login and this open source lol 😂😂 im not needs your fuckin data you are not important for me bro

Well could you at least add an option for those who don't want to log in?

**Comment by epicstudios856** [comment]
In coming updates i will add guest mode just wait next updates

**Comment by epicstudios856** [comment]
Privacy policy already added in roms manager page in first installation
