### ISSUE TITLE
kali linux x64 slow open & blsck screen

### ISSUE THREAD

**Issue by prajwol567** [epicstudios856/Vectras-VM-Android#21]
Help me , it edirated me
![Screenshot_2024-03-18-08-15-19-56_5eea71194e1a68a05fef1cb2e772635c](https://github.com/epicstudios856/Vectras-VM-Android/assets/163798478/73b26ab8-03ab-48a0-b3f2-8a05ada67ff3)

**Comment by prajwol567** [comment]
And lagging

**Comment by epicstudios856** [comment]
Its not issuse ur phone is low end
