### ISSUE TITLE
The kali linux issue not moving arrow & Stopping

### ISSUE THREAD

**Issue by prajwol567** [epicstudios856/Vectras-VM-Android#22]
Please help vectras team, my devicce ram is 6 gb then why the error show 
![Screenshot_2024-03-18-11-48-57-17_5eea71194e1a68a05fef1cb2e772635c](https://github.com/epicstudios856/Vectras-VM-Android/assets/163798478/fdb4e6a0-2119-44ad-ae8d-4277998964c7)

**Comment by prajwol567** [comment]
Fast solved  it

**Comment by Mikasa8324** [comment]
Join telegram and ask it there may be you find solution
