### ISSUE TITLE
S24 ultra error win xp

### ISSUE THREAD

**Issue by JairMartinez86** [epicstudios856/Vectras-VM-Android#23]
Time Of Crash :    2024_03_19-22_31_26
Device :    samsung, SM-S928B
Android Version :    14 (34)
App Version :    v2.8-debug-build-3 (13)
Kernel :    /proc/version: open failed: EACCES (Permission denied)
Support Abis :    [arm64-v8a]
Fingerprint :    samsung/e3qxxx/e3q:14/UP1A.231005.007/S928BXXS1AXBL:user/release-keys

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.androidVNC.RfbProto.writeKeyEvent(int, int, boolean)' on a null object reference
	at android.androidVNC.VncCanvas.sendMetaKey1(VncCanvas.java:1192)
	at com.vectras.qemu.MainVNCActivity$43.run(MainVNCActivity.java:1225)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by epicstudios856** [comment]
@JairMartinez86 Thats not a bug

If u have an issue come to our tg discussion

https://t.me/vectras_vm_discussion
