### ISSUE TITLE
Blank screen 

### ISSUE THREAD

**Issue by Bisu172** [epicstudios856/Vectras-VM-Android#26]
I tried many os and softwares in app but when I tried to open it there is a landscape screen for a moment then it suddenly portrait and shows fully blank screen 
![Screenshot_2024-03-26-06-47-34-936_com vectras vm](https://github.com/epicstudios856/Vectras-VM-Android/assets/108627616/6f571b5a-7d5b-43ec-aa9a-5af70cbc3d99)
![Screenshot_2024-03-26-06-10-32-897_com vectras vm](https://github.com/epicstudios856/Vectras-VM-Android/assets/108627616/bdfcf9df-bcc3-4584-891f-7c68dbf9d45b)

**Comment by epicstudios856** [comment]
use 2.8
