### ISSUE TITLE
Hardware support?

### ISSUE THREAD

**Issue by RohitVerma882** [epicstudios856/Vectras-VM-Android#28]
How i can use hardware devices?

Like - Usb, mouse & keyboard

**Comment by RohitVerma882** [comment]
> @RohitVerma882 Yes
> 
> Keyboard works without configuration Mouse needs to run the rom and change resolution to be near to ur phone resolution and click options set mouse to external
> 
> And if u want to use usb devices u can use qemu redirect options

Whare is qemu redirect options?

**Comment by epicstudios856** [comment]
@RohitVerma882 open terminal within the app and type 'lsusb'
then put it in qemu params
'-usb -device usb-host,hostbus=<USB BUS>,hostaddr=3.1'

dont forget to replace '<USB BUS>' with ur usb bus
