### ISSUE TITLE
How to access usb

### ISSUE THREAD

**Issue by Ishu43642** [epicstudios856/Vectras-VM-Android#30]
When type in terminal lsusb permission denied 
![Screenshot_20240331_075728](https://github.com/epicstudios856/Vectras-VM-Android/assets/97582499/e2a25d84-1e41-493f-bad6-3963c8226fd3)

**Comment by epicstudios856** [comment]
@Ishu43642 U need root access to do it

But i think u can do it by using adb search about it

**Comment by epicstudios856** [comment]
Tell me exactly what u want to do

**Comment by Ishu43642** [comment]
Also tryed with root same issues

**Comment by epicstudios856** [comment]
@Ishu43642 Weird 

Try to search about it

I think u need to give the app permission for usb
