### ISSUE TITLE
Please wait for gpsvc

### ISSUE THREAD

**Issue by Hypergaming2020** [epicstudios856/Vectras-VM-Android#33]
Hello pls someone help me the app works great and it loads windows 11 but then It show this error:please wait for the gpsvc pls someone help mee plss

![Screenshot_20240406-001208_Vectras VM](https://github.com/epicstudios856/Vectras-VM-Android/assets/75438380/9b816bd4-8cd2-4b18-9c39-aeaf1dbe10f9)
Here is it

**Comment by epicstudios856** [comment]
@Hypergaming2020 Use latest build4 of 2.8 release

**Comment by Hypergaming2020** [comment]
Ok I tried the latest build4 of 2.8 release and it working here
![Screenshot_20240406-163714_Vectras VM](https://github.com/epicstudios856/Vectras-VM-Android/assets/75438380/56a38c1a-0769-4abc-a0d0-0638cacd8da1)
But then It crashes I tried multiple times but still crashes and shows this
![Screenshot_20240406-170014_Vectras VM](https://github.com/epicstudios856/Vectras-VM-Android/assets/75438380/60157c01-fc9b-4ee5-ab14-6536f5e53902)
And I'm using two devices one is rddmi 9 and two samsung tab a7 they both have 3gb ram and both have android 12 version

**Comment by epicstudios856** [comment]
@Hypergaming2020 I told u use 2.8 build 4 + win11 is very powerful u need 1²gb ram as minimum

**Comment by Hypergaming2020** [comment]
I am using it

**Comment by epicstudios856** [comment]
@Hypergaming2020 Sorry, u r using 2.8.3 , i know my fkn app

**Comment by epicstudios856** [comment]
In 2.8 release section
