### ISSUE TITLE
App not running the vbi file lineagos android 12

### ISSUE THREAD

**Issue by javafixer** [epicstudios856/Vectras-VM-Android#39]
Idk if it’s loading or it’s broken

https://github.com/epicstudios856/Vectras-VM-Android/assets/76564225/5835ea62-d296-47e9-9d8e-1076fffb915f

**Comment by epicstudios856** [comment]
@javafixer The vbi is corrupted due server issues
Try another rom till we fix it

**Comment by javafixer** [comment]
Ok thanks for the reply just make it so it says error importing corrupted image thanks il try that later

**Comment by epicstudios856** [comment]
@javafixer Ok
