### ISSUE TITLE
Quick shortcut for apps

### ISSUE THREAD

**Issue by GithubUser559** [epicstudios856/Vectras-VM-Android#41]
Add a shortcut to directly open .exe apps instead of going through opening the system and manually going to the file manager to open it. How to do it?: Add an Option to add apps.then Ask the user On what system will the .exe be executed And instead of directly loading the system startup. Directly load the app on the system automatically

**Comment by epicstudios856** [comment]
@GithubUser559 Thats not wine, thats qemu


Use wine emulator instead
