### ISSUE TITLE
Windows 7 64x

### ISSUE THREAD

**Issue by LadiOnTheBeat** [epicstudios856/Vectras-VM-Android#44]
![Screenshot_20240419-231349_Vectras VM](https://github.com/epicstudios856/Vectras-VM-Android/assets/167113270/58fdc604-74c0-4f4d-b7e1-7ac131772a14)
When i launch Windows 7 there is only black screen

**Comment by epicstudios856** [comment]
@LadiOnTheBeat try reimport and dont close the app

**Comment by Herobrine153** [comment]
> ![Screenshot_20240419-231349_Vectras VM](https://private-user-images.githubusercontent.com/167113270/324119641-58fdc604-74c0-4f4d-b7e1-7ac131772a14.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2ODAyMDIsIm5iZiI6MTcxMzY3OTkwMiwicGF0aCI6Ii8xNjcxMTMyNzAvMzI0MTE5NjQxLTU4ZmRjNjA0LTc0YzAtNGY0ZC1iN2UxLTdhYzEzMTc3MmExNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMVQwNjExNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzM0ZjE2NzljNWIyNWRlNDIzYTc4ZTM2YThjMWYwYWI3NTVhNzMyMGFjMWI3ZmQ0MGExMDcyZmRiNjdmNjBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VwfNGrsLsk4CYjQj_nsP1QnaDLMr6YpdvQ-EHEp-buY) When i launch Windows 7 there is only black screen

**Comment by KAMELCOLTD** [comment]
same problem win 7 64bit not working only black screen v 2.7
Samsung note 10 plus android 10

**Comment by epicstudios856** [comment]
Use 2.9.0
