### ISSUE TITLE
General crash

### ISSUE THREAD

**Issue by ReGiulio** [epicstudios856/Vectras-VM-Android#46]
Time Of Crash :    2024_04_20-14_00_02
Device :    samsung, SM-A346B
Android Version :    14 (34)
App Version :    v2.8-debug-build-5 (15)
Kernel :    /proc/version: open failed: EACCES (Permission denied)
Support Abis :    [arm64-v8a, armeabi-v7a, armeabi]
Fingerprint :    samsung/a34xeea/a34x:14/UP1A.231005.007/A346BXXS5BWL2:user/release-keys

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.androidVNC.RfbProto.writeKeyEvent(int, int, boolean)' on a null object reference
	at android.androidVNC.VncCanvas.sendMetaKey1(VncCanvas.java:1203)
	at com.vectras.qemu.MainVNCActivity$43.run(MainVNCActivity.java:1162)
	at java.lang.Thread.run(Thread.java:1012)

I tried on various Linux operating systems and it crashed all the time, except for Mint, but it still didn't show what it was supposed to (in this report i used temple OS, not exactly Linux but still similar)

**Comment by epicstudios856** [comment]
Check view logs

**Comment by epicstudios856** [comment]
Use 2.9.0
