### ISSUE TITLE
VM not loading 

### ISSUE THREAD

**Issue by sherrygamerz** [epicstudios856/Vectras-VM-Android#48]
I have tried to install windows 11 then try to run but it doesn't run, Loads for ever what i do? Now

**Comment by epicstudios856** [comment]
Its very heavy and u need for example 8gb free ram and 8gen3 to get medium performance, keep in mind u  running x86_64 vm machine on aarch64 mobile.


qemu.org

**Comment by mrfoxie** [comment]
mine is stck on this
![Screenshot_20240423_015300_Vectras VM](https://github.com/epicstudios856/Vectras-VM-Android/assets/25217451/ad3dc400-c6cb-4ca3-a036-2a22acba5db2)
