### ISSUE TITLE
Rom not getting installed

### ISSUE THREAD

**Issue by prathikjk** [epicstudios856/Vectras-VM-Android#54]
App is opening with errors also it is not showing installed rom file when I tried to import rom file from device.

![Screenshot_20240430-225943](https://github.com/epicstudios856/Vectras-VM-Android/assets/81760324/82d9d3d7-5b46-4440-9268-db8c9cf7e16e)

![Screenshot_20240430-233518](https://github.com/epicstudios856/Vectras-VM-Android/assets/81760324/ed296dc9-ce8e-4d23-ab8c-04678b6d2137)
![Screenshot_20240430-231249](https://github.com/epicstudios856/Vectras-VM-Android/assets/81760324/c5dd9090-70d4-453b-aca6-001150d5854c)
![Screenshot_20240430-231252](https://github.com/epicstudios856/Vectras-VM-Android/assets/81760324/3644c255-2b66-4919-b643-a38225c98b8a)

**Comment by epicstudios856** [comment]
Dont exit app while it importing!!!!!
