### ISSUE TITLE
Command Failed with exit code: 1

### ISSUE THREAD

**Issue by logicallyanime** [epicstudios856/Vectras-VM-Android#55]
App Version: 2.5-debug-build-5
OS: Android 12
Device: Samsung Galaxy Tab S8 Ultra (SM-X900)

Receiving 'Command Failed' error when installing bootstrap. Error is consistent whether Auto Setup or Manual Setup is selected.
![Screenshot_20240502-181911_Gallery](https://github.com/epicstudios856/Vectras-VM-Android/assets/56837225/2efbef22-0ba3-4795-b1fa-d47b5b5b7e99)

**Comment by epicstudios856** [comment]
@logicallyanime thats  means no bug, restart the app

**Comment by logicallyanime** [comment]
> @logicallyanime thats means no bug, restart the app

Ah ok I guess i just assumed that that was why i was having my other issue, I am having issues running the Mac 10.5 and 10.4 roms. When ran the app just gives me a black screen.

**Comment by logicallyanime** [comment]
> @logicallyanime thats means no bug, restart the app
@epicstudios856 
Ah ok I guess i just assumed that that was why i was having my other issue, I am having issues running the Mac 10.5 and 10.4 roms. When ran the app just gives me a black screen.

**Comment by epicstudios856** [comment]
@logicallyanime Shhow me the logs from 3lines button
