### ISSUE TITLE
ERROR : org.json.JSONException: Value error of type java.lang.String cannot be converted to JSONArray

### ISSUE THREAD

**Issue by HussenXD** [epicstudios856/Vectras-VM-Android#56]
App Version: 2.5-debug-build-5
OS: Android 12
Device: Redmi K30 pro / poco f2 pro
issue 
when i went to download any rom it give me that error
org.json.JSONException: Value error of type
java.lang.String cannot be converted to JSONArray
and no rom showing to me
![Screenshot_2024-05-06-08-23-45-571-edit_com vectras vm](https://github.com/epicstudios856/Vectras-VM-Android/assets/94928823/201166bf-78af-45d9-8100-e353d1292735)

thank you for your hard work it is very rare that we have people like you guys 🥀

**Comment by Fercho314** [comment]
I have the same problem in a Xiaomi Redmi 9T, with custum room.

**Comment by epicstudios856** [comment]
@HussenXD We have discontinued the project, u can only use it with custom roms like limbo, etc...

**Comment by Efscb1343** [comment]
Me too I Have the same problem 😞
![Uploading Screenshot_2024-05-06-22-51-29-68_5eea71194e1a68a05fef1cb2e772635c.jpg…]()

**Comment by ZahidAsif** [comment]
Same Issue. Yesterday morning it was all ok, populated with OS lists, but today its saying JSON error. no list. so no import possible. tried uninstalling VM two times, no luck, tried installing the lite version too, same issue. 

@epicstudios856 do you think this project will be up again ?

**Comment by ZahidAsif** [comment]
Direct link to roms page, https://vectrasvm.blackstorm.cc/roms.html, ... i ll be trying downloading it on PC, saving to mobile and adding manually. can anyone share parameters for xp64bit ?

**Comment by epicstudios856** [comment]
@ZahidAsif We stopped rom manager due copyright issues, use custom rom
