### ISSUE TITLE
Installation failing, premature crash during install.

### ISSUE THREAD

**Issue by ZahidAsif** [epicstudios856/Vectras-VM-Android#57]
Amazing app, it was working good two days ago, on the same mobile just re-installed it after finding missing roms listing. but now unable to install. it says OK 29980 packages avlbl.  app exit code 1. I tried adding manual rom, but fails during boot. 
![Screenshot_20240507-130020_Vectras VM](https://github.com/epicstudios856/Vectras-VM-Android/assets/42314129/fc446c55-da2d-492f-af3d-afb1df51809a)
![Screenshot_20240507-130401_Vectras VM](https://github.com/epicstudios856/Vectras-VM-Android/assets/42314129/620c62c1-929f-4881-9aea-0d7b3a38edfa)

**Comment by epicstudios856** [comment]
Show me ur custom rom configuration

**Comment by ZahidAsif** [comment]
![Uploading Screenshot_20240509-105820_Vectras VM.jpg…]()

**Comment by ZahidAsif** [comment]
![Screenshot_20240509-105820_Vectras VM](https://github.com/epicstudios856/Vectras-VM-Android/assets/42314129/f038f72e-d6aa-418b-9a91-b557d024670d)

**Comment by ZahidAsif** [comment]
i think the default QEMU parameters are not working for XPx64 ?

**Comment by ZahidAsif** [comment]
I tried a clean re-install, (fresh download of apk, fresh download of vbi), this time installation completed i think. (it gave exitcode1), after a lot of processes. .... my OS listing is blank and gives same JSON error, is there any solution to this ?? I am not getting listing in android, so i have to go to pc to download rom, copy it manually to phone, and then add in custom-rom option. pl tell if i am doing something wrong here.
