### ISSUE TITLE
Vectras VM not working Android 14 hyper os

### ISSUE THREAD

**Issue by emiremirkk** [epicstudios856/Vectras-VM-Android#58]
I downloaded the last version that was debug and I pressed auto install it did install but at the end it errored and I didn't see what's the error about because it showed the error for a second.it didn't work there was no windows Mac os Linux or anything other it just gave this error wherever I tap: | org.json.JSONException: Value error of type java.lang.String cannot be converted to JSONArray | I tried the non debug version but it was the same error and when I was on the login it said that I wasn't connected to the internet but I was I tried different internet connections but I got nothing.I have a redmi note 12 pro 5G and it's running Android 14 hyper os.Can anyone help?

**Comment by emiremirkk** [comment]
![Screenshot_2024-05-07-11-19-00-235_com vectras vm](https://github.com/epicstudios856/Vectras-VM-Android/assets/97346875/eac67ffc-295c-4e3d-996f-0ec3a977b8f2). Heres a screenshot

**Comment by emiremirkk** [comment]
Also when installing with auto install at the end it gave me this error: Command Failed with exit code: 1

**Comment by emiremirkk** [comment]
We can chat on discord if you want user:emiremirkkyt

**Comment by epicstudios856** [comment]
We stopped rom manager due copyright issues, use custom rom

**Comment by emiremirkk** [comment]
Ok

**Comment by Zeph794** [comment]
I cant even install the latest vectrasvm 2.9.0 on hyperos it says package is invalid

**Comment by epicstudios856** [comment]
Redownload

> I cant even install the latest vectrasvm 2.9.0 on hyperos it says package is invalid
