### ISSUE TITLE
App error

### ISSUE THREAD

**Issue by Loading617** [epicstudios856/Vectras-VM-Android#60]
![Screenshot_20240511_171136_Vectras VM.jpg](https://github.com/epicstudios856/Vectras-VM-Android/assets/89672772/fa536278-fd34-49cb-9125-5f298fa6bef3)

**Comment by MatejMagat305** [comment]
org.json.JSONException error, it is not load vm s ...

**Comment by willbertpan** [comment]
org.json.JSONException: Value error of type java.lang.String cannot be converted to JSONArray

**Comment by epicstudios856** [comment]
Use 2.9.0
