### ISSUE TITLE
Adding Xp 64 as custom rom, ... failing during rom boot,

### ISSUE THREAD

**Issue by ZahidAsif** [epicstudios856/Vectras-VM-Android#64]
![Screenshot_20240509-105820_Vectras VM](https://github.com/epicstudios856/Vectras-VM-Android/assets/42314129/7eacc612-5346-4ba4-ad79-f471611e1ac4)
I think default QEMU parameters are not being accepted by XP64 rom. .... i think i have a clean fresh install of apk working here. (did a very clean install, its my 25th try to get it working since last two days) dont know what i am doing wrong here.

**Comment by ZahidAsif** [comment]
can u kindly share the QEMU parameters for XP64 ?

**Comment by ZahidAsif** [comment]
i have tried following: 
-device VGA,vgamem_mb=64 -cpu host -accel kvm -M pc -netdev user,id=lan -device rtl8139,netdev=lan -usb -device usb-tablet -rtc base=localtime -monitor stdio

-m 512 -device VGA,vgamem_mb=64 -cpu host -accel kvm -netdev user,id=lan -device rtl8139,netdev=lan -usb -device usb-tablet -rtc base=localtime -monitor stdio

but no success.

**Comment by ZahidAsif** [comment]
vbi .... its complete filename is  txpx64.vbi sized at 1.18 GB

**Comment by ZahidAsif** [comment]
![2024-05-10 11_05_52-SM-G965U](https://github.com/epicstudios856/Vectras-VM-Android/assets/42314129/46aff032-b9f7-4c44-9a88-8cb84a0209cd)

**Comment by ZahidAsif** [comment]
i downloaded it from https://vectrasvm.blackstorm.cc/roms.html roms page, link to the file is https://drive.google.com/file/d/13dDHYc6j_LrCUwcwL9L-pm4DZQ3gqm5C/view

**Comment by ZahidAsif** [comment]
![2024-05-10 11_55_11-](https://github.com/epicstudios856/Vectras-VM-Android/assets/42314129/bab6e282-6775-4745-a90d-5795d3b0b40e)
![2024-05-10 11_57_14-SM-G965U](https://github.com/epicstudios856/Vectras-VM-Android/assets/42314129/74683cd8-61d6-4245-afdb-f37d2d66d8f1)
![2024-05-10 11_57_54-Re_ - zahid asif@gmail com - Gmail](https://github.com/epicstudios856/Vectras-VM-Android/assets/42314129/b8e26e97-effa-4225-89ae-d47ddf7eb303)


i tried loading windows xp86 also, ... same issue, then i tried loading win3.1 ... same issue.

**Comment by ZahidAsif** [comment]
I am confirm that only QEMU parameters are messing up. .... i tried -vga cirrus -nic user,model=e1000 ... .did not work.

**Comment by aracnotech** [comment]
You have to unpack txpx64.vbi file with zarchiver, you will obtain txpx64.IMG and put it in ROM DRIVE . Leave the default QEMU parameters.

**Comment by epicstudios856** [comment]
U have to unpack the vbi
