### ISSUE TITLE
exit code: 1

### ISSUE THREAD

**Issue by ItsNeverLight** [epicstudios856/Vectras-VM-Android#66]
Using POCO X6 PRO, ANDROID 14 HYPEROS with magisk root.![Screenshot_2024-05-10-12-43-25-228_com.vectras.vm.jpg](https://github.com/epicstudios856/Vectras-VM-Android/assets/48273622/f8d6e64a-ee28-4cde-8e89-60363ef9944b)

**Comment by epicstudios856** [comment]
Ur cpu does not support armeabi-v7a so we working on fix it

**Comment by epicstudios856** [comment]
Duplicated issue:
https://github.com/epicstudios856/Vectras-VM-Android/issues/49
