### ISSUE TITLE
org.json.JSONException: Value error of type java.lang.String cannot be converted to JSONArray

### ISSUE THREAD

**Issue by dentalinab** [epicstudios856/Vectras-VM-Android#67]
![Screenshot_20240510-193059_Vectras VM](https://github.com/epicstudios856/Vectras-VM-Android/assets/169479650/c84d0376-05fa-4b21-a806-be4cf5ce9b73)

The app wont let me choose the kernel and nothing is showing whatever I select

**Comment by CJCameHome** [comment]
Same thing happened to me

**Comment by Ashishgud** [comment]
Same in samsung a52s 5g android 14

**Comment by aracnotech** [comment]
You have to add custom rom manually:
https://youtu.be/-dITPy--h6Q?feature=shared

**Comment by epicstudios856** [comment]
Use 2.9.0
