### ISSUE TITLE
Exit Code : 2

### ISSUE THREAD

**Issue by Thoufeeq0000** [epicstudios856/Vectras-VM-Android#68]
I Don't No What is This Please Help Me

Device : Poco X3 Pro
Processor : Snapdragon 860 
Android Version : 11
OS : MIUI 12.0.4.0

![Uploading Screenshot_2024-05-11-11-35-43-160_com.vectras.vm.jpg…]()

Lastest Build Of Vectras VM

**Comment by Thoufeeq0000** [comment]
![Uploading Screenshot_2024-05-11-11-35-43-160_com.vectras.vm.jpg…]()

**Comment by Thoufeeq0000** [comment]
Issue : 
Executing pipewire-1.0.0-r0.post-install

(55/75) Installing libnl3 (3.9.0-r1)

(56/75) Installing rdma-core-libs (49.0-r0)

(57/75) Installing rdma-core (49.0-r0)

(58/75) Installing perl (5.38.2-r0)

(59/75) Installing libice (1.1.1-r5)

(60/75) Installing libsm (1.2.4-r3)

(61/75) Installing libxt (1.3.0-r4)

(62/75) Installing libxmu (1.1.4-r2)

(63/75) Installing xauth (1.1.2-r1)

(64/75) Installing mcookie (2.39.3-r0)

(65/75) Installing xmodmap (1.0.11-r1)

(66/75) Installing xrdb (1.2.2-r0)

(67/75) Installing xinit (1.4.2-r1)

(68/75) Installing libxkbfile (1.1.3-r0)

(69/75) Installing xkbcomp (1.4.7-r0)

(70/75) Installing libfontenc (1.1.7-r4)

(71/75) Installing libxfont2 (2.0.6-r3)

(72/75) Installing skalibs (2.14.0.1-r0)

(73/75) Installing utmps-libs (0.1.2.2-r0)

(74/75) Installing linux-pam (1.5.3-r7)

(75/75) Installing tigervnc (1.13.1-r4)

Executing busybox-1.36.1-r15.trigger

Executing ca-certificates-20240226-r0.trigger

Executing fontconfig-2.14.2-r4.trigger

Executing glib-2.78.5-r0.trigger

Executing shared-mime-info-2.4-r0.trigger

Executing gdk-pixbuf-2.42.10-r6.trigger

Executing gtk-update-icon-cache-3.24.41-r0.trigger

Executing gtk+3.0-3.24.41-r0.trigger

OK: 706 MiB in 278 packages

usr/

usr/local/

usr/local/lib/

usr/local/lib/libslirp.so.0.4.0

gzip: unexpected end of file

tar: Unexpected EOF in archive

tar: Unexpected EOF in archive

tar: Error is not recoverable: exiting now

Error: Command failed with exit code: 2

**Comment by Thoufeeq0000** [comment]
Uploading Screenrecorder-2024-05-11-11-41-29-632.mp4…

**Comment by Thoufeeq0000** [comment]
Image is not uploading

**Comment by epicstudios856** [comment]
Use 2.9.0 and use manual install
