### ISSUE TITLE
String cannot be converted

### ISSUE THREAD

**Issue by spyhunter1288** [epicstudios856/Vectras-VM-Android#69]
Please help after patching it shows error 01 and after that it doesn't show any rom
![Screenshot_20240511-214028](https://github.com/epicstudios856/Vectras-VM-Android/assets/129369686/478fee46-8a61-453b-8118-a8d4591ccc8f)

**Comment by epicstudios856** [comment]
Update to 2.9.0

**Comment by spyhunter1288** [comment]
> Update to 2.9.0

Thanks 😇
