### ISSUE TITLE
Things to fix in the app

### ISSUE THREAD

**Issue by ahmedbarakat2007** [epicstudios856/Vectras-VM-Android#79]
1) The Loop in Booting up
2) Unable to Close the Session from Notification
3) Useless Arm, PPC CPUs (ppc should be only g4 and g3 on -M mac99 and arm should only be cortex-a53 and cortex-a57)
4) No Custom Rom Menu (Like Create QEMU Commands (THIS IS FU*KING IMPORTANT bcuz not everyone understand Qemu Params))
5) Nothing Works at all
6) using -cpu qemu64 on qemu-system-i386 (LOL)
7) Unable to change anything from Settings (It Returns back to Default)
8) Unable to Change Anything from Modify Rom (Also Returns back to Default)
9) There is a Space Between "nic" and ",model" in "-net nic,model=..." (Makeing the app useless because i can't change it)
10) -monitor should be stdio not vc in qemu-system-aarch64

and these are the i discoverd for now

**Comment by epicstudios856** [comment]
When u switch the kosom elarch he inviting bug ya ro7 ko****

**Comment by ahmedbarakat2007** [comment]
STILL THAT'S NOT MY FUCKING ISSUE FIND A SOLUTION FOR IT

**Comment by epicstudios856** [comment]
> STILL THAT'S NOT MY FUCKING ISSUE FIND A SOLUTION FOR IT

Fuck u

**Comment by epicstudios856** [comment]
fixed
