### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Mrfrulzraj** [epicstudios856/Vectras-VM-Android#83]
![Screenshot_20240513_211633_Vectras VM](https://github.com/epicstudios856/Vectras-VM-Android/assets/117901827/1b178291-eb9b-43dc-bbc0-bf2903bb848c)

**Comment by epicstudios856** [comment]
Duplicated issue:
https://github.com/epicstudios856/Vectras-VM-Android/issues/49

**Comment by Mrfrulzraj** [comment]
What I can do.?

**Comment by epicstudios856** [comment]
Read the issue
