### ISSUE TITLE
Booting issues 

### ISSUE THREAD

**Issue by Igsankya24** [epicstudios856/Vectras-VM-Android#87]
VTERM ERROR: >qemu-system-x86_64:-drive fle=/storage/emulated/0/Android/data/com.vectras.vm/hles/data/Vectras/10/10.qcow2,aio=threads,cache=unsafe,if=virtio: Could not open '/storage/emulated/0/Android/data/com.vectras.vm/fles/data/Vectras/10/10.qcow2': No such file or directory
![Uploading Screenshot_2024-05-18-12-49-38-544_com.vectras.vm.jpg…]()

**Comment by Igsankya24** [comment]
![Uploading Screenshot_2024-05-18-12-49-38-544_com.vectras.vm.jpg…]()

**Comment by epicstudios856** [comment]
**'/storage/emulated/0/Android/data/com.vectras.vm/fles/data/Vectras/10/10.qcow2': No such file or directory**

Make sure the files is exist, copy it manually

**Comment by Igsankya24** [comment]
Which file need to be copied

**Comment by epicstudios856** [comment]
@Igsankya24 10.qcow2
