### ISSUE TITLE
Error code 1

### ISSUE THREAD

**Issue by ArmandasK** [epicstudios856/Vectras-VM-Android#88]
App installs, whether i'm using manual or auto it wont setup itself, poco x6 pro android 14 x hyperos
![Screenshot_2024-05-18-15-36-40-414_com vectras vm](https://github.com/epicstudios856/Vectras-VM-Android/assets/170182093/5f7cf76f-003a-4d8e-9c5d-39894d1b9296)

**Comment by epicstudios856** [comment]
Ur cpu not supported yet
