### ISSUE TITLE
Ressources for adding KVM to Kernel

### ISSUE THREAD

**Issue by ne0YT** [epicstudios856/Vectras-VM-Android#9]
maybe someone can share ressources on how to add KVM Support to the Kernel when compiling. If there is a general way.
Or maybe there's a list of KVM-enabled Kernels ready to flash somewhere?

**Comment by epicstudios856** [comment]
First find ur phone frimware os and search in github for kvm for ur phone model u will find instructions there

**Comment by epicstudios856** [comment]
2.7 only supports kvm for x86 devices

Wait for 2.8 for all phone support

**Comment by ne0YT** [comment]
> 2.7 only supports kvm for x86 devices
> 
> Wait for 2.8 for all phone support

Can you find for Oneplus 11 pro?

**Comment by ne0YT** [comment]
@epicstudios856 maybe you can guide me some more to get KVM working on OP11?

**Comment by epicstudios856** [comment]
vectras still not support kvm for arm mobiles.

**Comment by ne0YT** [comment]
@epicstudios856 why closing as complete?
