### ISSUE TITLE
The rom in the store is invalid

### ISSUE THREAD

**Issue by GuythatUhmCreatesRandomStuff** [epicstudios856/Vectras-VM-Android#90]
(The beginning is just me figuring out how to import a rom so ignore that stupid me)
the rom is in the store
I select the qcow2 and the cvbi file but the rom is still aint bootable.

Just wtf.

https://github.com/epicstudios856/Vectras-VM-Android/assets/144390627/2936dfbd-675b-45b7-a61f-6777d77bbef4

ill try testing the limbo emulator cuz why not

**Comment by epicstudios856** [comment]
Use the stupid button on top of screen, u read rom description in store?!!!

**Comment by GuythatUhmCreatesRandomStuff** [comment]
> Use the stupid button on top of screen, u read rom description in store?!!!

Dawg thanks
