### ISSUE TITLE
App is not compatible with Samsung Galaxy Fold 3

### ISSUE THREAD

**Issue by shaunroselt** [epicstudios856/Vectras-VM-Android#95]
I downloaded the [latest release](https://github.com/epicstudios856/Vectras-VM-Android/releases/download/v2.9.1-fix2/app-x86_64-release.apk) and tried to install it on my Samsung Galaxy Fold 3, but then I instantly get an error that says:

> Vectras VM
> App not installed as app isn't compatible with your phone

![Vectras VM - App not installed as app isn't compatible with your phone](https://github.com/epicstudios856/Vectras-VM-Android/assets/5418178/0066197f-f78d-4056-8e07-897ca245ba07)

I'm running Android 14 with OneUI 6.1 on my Samsung Galaxy Fold 3:

![Software Information](https://github.com/epicstudios856/Vectras-VM-Android/assets/5418178/6aa4911c-1def-4b4c-9c13-8f611ece0367)

**Comment by epicstudios856** [comment]
arm7??

**Comment by iLagTooMuch** [comment]
> arm7??

You think a recent flagship device is going to have arm7?

**Comment by epicstudios856** [comment]
> > arm7??
> 
> You think a recent flagship device is going to have arm7?

Yeah i seen alot of weird shit, sorry the app installed on all fold series so its ur problem
